### ISSUE TITLE
Generator breaks gulp ?

### ISSUE THREAD

**Issue by kelexel** [PolymerElements/generator-polymer-init-custom-build#46]
OSX 10.11.6,

Freshly installed polymer-cli and generator-polymer-init-custom-buid

But...

```
prometheus3:app3 rud$ nvm --version
0.32.1
prometheus3:app3 rud$ node --version
v6.9.1
prometheus3:app3 rud$ npm --version
3.10.8
prometheus3:app3 rud$ gulp --version
[12:33:33] CLI version 3.9.1
[12:33:33] Local version 4.0.0-alpha.2
prometheus3:app3 rud$
prometheus3:app3 rud$ ls
CONTRIBUTING.md		README.md		bower_components	gulpfile.js		index.html		node_modules		polymer.json		src			test
LICENSE.txt		bower.json		gulp-tasks		images			manifest.json		package.json		service-worker.js	sw-precache-config.js
prometheus3:app3 rud$
prometheus3:app3 rud$ gulp
[12:33:54] Using gulpfile ~/Desktop/Dev/lamp/app3/gulpfile.js
/Users/rud/.nvm/versions/node/v6.9.1/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/rud/.nvm/versions/node/v6.9.1/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Of course I use the same gulp and gulp-cli version on other projects fine, but it borks with this generator :/

**Comment by abdonrd** [comment]
Duplicated with https://github.com/PolymerElements/generator-polymer-init-custom-build/issues/44 and fixed with https://github.com/PolymerElements/generator-polymer-init-custom-build/pull/41. :)

**Comment by kelexel** [comment]
Oh, forgive me, I see it was merged 13 hours ago...
But than, why am I today still getting the "buggy" generator from "npm install -g generator-polymer-init-custom-buid" ?

**Comment by abdonrd** [comment]
@kelexel we need to release a new version to npm. Maybe @robdodson can help us. :)

**Comment by kelexel** [comment]
@abdonrd oh, understood, thank you ;)
Will invoke gulp from ./node_modules/.bin/ meanwhile.

**Comment by robdodson** [comment]
just published a new version to npm
